/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Check if the app has Screen Capture (Screen Recording) access. */
export declare function hasScreenCaptureAccess(): boolean

/**
 * Check if system audio capture is supported on this platform.
 * Requires macOS 14.2+ (Sonoma).
 */
export declare function isSupported(): boolean

/** Request Screen & System Audio Recording permission via ScreenCaptureKit. */
export declare function requestAudioCapturePermission(): boolean

/** Request Screen Capture access (triggers macOS permission dialog). */
export declare function requestScreenCaptureAccess(): boolean

/**
 * Start capturing system audio via ScreenCaptureKit.
 * The callback receives Buffer chunks of 16kHz mono Int16 PCM data.
 */
export declare function startCapture(callback: ((err: Error | null, arg: Buffer) => any)): void

/** Stop capturing system audio. Cleans up all resources. */
export declare function stopCapture(): void
